services:
  - type: web
    name: kp-enterprises-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
